name: oil_monitorin
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.3
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  flutter_launcher_icons: ^0.14.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/icon/

flutter_launcher_icons:
  android: "ic_launcher" # Nama file icon di Android
  ios: true              # Generate juga untuk iOS
  image_path: "assets/icon/app_icon.png" # Lokasi gambar ikon Anda
  adaptive_icon_background: "#1E1E1E"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  adaptive_icon_monochrome: "assets/icon/app_icon_monochrome.png"